export const InvoiceMapping = [
  {
    value: "Chetak",
    slug: "chetak",
    jsonName: "chetak-products.json",
    emptyColumn: true,
    databaseName: "chetakproducts",
  },
  // {value:'',slug:'',jsonName:'aahubarah.json',emptyColumn:false,databaseName:'aahubarahs'},
  // {value:'',slug:'',jsonName:'adelaman-food.json',emptyColumn:false,databaseName:'adelamanfoods'},
  {
    value: "Advance Foods",
    slug: "advance-foods",
    jsonName: "advance-foods.json",
    emptyColumn: false,
    databaseName: "advancefoods",
  },
  // {value:'',slug:'',jsonName:'aliments.json',emptyColumn:false,databaseName:'aliments'},
  // {value:'',slug:'',jsonName:'amtrade.json',emptyColumn:false,databaseName:'amtrades'},
  // {value:'',slug:'',jsonName:'anmol-distribution.json',emptyColumn:false,databaseName:'anmoldistributions'},
  // {value:'',slug:'',jsonName:'anns-eco-store.json',emptyColumn:false,databaseName:'annsecostores'},
  // {value:'',slug:'',jsonName:'babco.json',emptyColumn:false,databaseName:'babcos'},
  // {value:'',slug:'',jsonName:'baraka-cold.json',emptyColumn:false,databaseName:'barakacolds'},
  // {value:'',slug:'',jsonName:'barlett.json',emptyColumn:false,databaseName:'barletts'},
  // {value:'',slug:'',jsonName:'baroody.json',emptyColumn:false,databaseName:'baroodies'},
  // {value:'',slug:'',jsonName:'bartlett.json',emptyColumn:false,databaseName:'bartletts'},
  // {value:'',slug:'',jsonName:'bedessee.json',emptyColumn:false,databaseName:'bedessees'},
  // {value:'',slug:'',jsonName:'Best-food-1.json',emptyColumn:false,databaseName:'bestfood1'},
  {
    value: "Best Foods",
    slug: "best-foods",
    jsonName: "best-foods.json",
    emptyColumn: true,
    databaseName: "bestfoods",
  },

  // {value:'',slug:'',jsonName:'dara.json',emptyColumn:false,databaseName:'daras'},
  // {value:'',slug:'',jsonName:'dawn-food.json',emptyColumn:false,databaseName:'dawnfoods'},
  // {value:'',slug:'',jsonName:'delight-distrubution.json',emptyColumn:false,databaseName:'delightdistrubutions'},
  // {value:'',slug:'',jsonName:'delight-foods.json',emptyColumn:false,databaseName:'delightfoods'},
  // {value:'',slug:'',jsonName:'dsa-snacks.json',emptyColumn:false,databaseName:'dsasnacks'},
  // {value:'',slug:'',jsonName:'east-end.json',emptyColumn:false,databaseName:'eastends'},
  // {value:'',slug:'',jsonName:'empire-food-importers.json',emptyColumn:false,databaseName:'empirefoodimporters'},
  // {value:'',slug:'',jsonName:'family-five.json',emptyColumn:false,databaseName:'familyfives'},
  // {value:'',slug:'',jsonName:'galil-importing.json',emptyColumn:false,databaseName:'galilimportings'},
  // {value:'',slug:'',jsonName:'goyal-grp.json',emptyColumn:false,databaseName:'goyalgrps'},
  // {value:'',slug:'',jsonName:'grocermill.json',emptyColumn:false,databaseName:'grocermills'},
  // {value:'',slug:'',jsonName:'hellenic.json',emptyColumn:false,databaseName:'hellenics'},
  // {value:'',slug:'',jsonName:'hill-top-farms.json',emptyColumn:false,databaseName:'hilltopfarms'},
  // {value:'',slug:'',jsonName:'house-spices.json',emptyColumn:false,databaseName:'housespices'},
  // {value:'',slug:'',jsonName:'india-food-spices.json',emptyColumn:false,databaseName:'indiafoodspices'},
  // {value:'',slug:'',jsonName:'indian-spice-trading.json',emptyColumn:false,databaseName:'indianspicetradings'},
  // {value:'',slug:'',jsonName:'I-sifol-llc.json',emptyColumn:false,databaseName:'isifolllcs'},
  // {value:'',slug:'',jsonName:'jaan-dist.json',emptyColumn:false,databaseName:'jaandists'},
  // {value:'',slug:'',jsonName:'jalaram.json',emptyColumn:false,databaseName:'jalarams'},
  // {value:'',slug:'',jsonName:'jcw-import.json',emptyColumn:false,databaseName:'jcwimports'},
  // {value:'',slug:'',jsonName:'joy-foods.json',emptyColumn:false,databaseName:'joyfoods'},
  {
    value: "Joy gourmet foods",
    slug: "joy-gourmet-foods",
    jsonName: "joy-gourmet-foods.json",
    emptyColumn: false,
    databaseName: "joygourmetfoods",
  },
  {
    value: "Katzman",
    slug: "katzman",
    jsonName: "katzman.json",
    emptyColumn: false,
    databaseName: "katzmen",
  },
  // {value:'',slug:'',jsonName:'km-dist-usa.json',emptyColumn:false,databaseName:'kmdistusas'},
  // {value:'',slug:'',jsonName:'koryeo-foods.json',emptyColumn:false,databaseName:'koryeofoods'},
  // {value:'',slug:'',jsonNaseame:'krino-foods.json',emptyColumn:false,databaseName:'krinofoods'},
  {
    value: "Krishna Foods",
    slug: "krishna-foods",
    jsonName: "krishna-foods-products.json",
    emptyColumn: false,
    databaseName: "krishnafoodsproducts",
  },
  // {value:'',slug:'',jsonName:'krishna.json',emptyColumn:false,databaseName:'krishnas'},
  // {value:'',slug:'',jsonName:'leblon.json',emptyColumn:false,databaseName:'leblons'},
  // {value:'',slug:'',jsonName:'loumidis-food.json',emptyColumn:false,databaseName:'loumidisfoods'},
  // {value:'',slug:'',jsonName:'maharaja.json',emptyColumn:false,databaseName:'maharajas'},
  // {value:'',slug:'',jsonName:'meenaxi.json',emptyColumn:false,databaseName:'meenaxis'},
  // {value:'',slug:'',jsonName:'mel-icecream.json',emptyColumn:false,databaseName:'melicecreams'},
  // {value:'',slug:'',jsonName:'moda-food-ny.json',emptyColumn:false,databaseName:'modafoodnies'},
  // {value:'',slug:'',jsonName:'mr-pickle.json',emptyColumn:false,databaseName:'mrpickles'},
  // {value:'',slug:'',jsonName:'my-baby-ev.json',emptyColumn:false,databaseName:'mybabyevs'},
  // {value:'',slug:'',jsonName:'nassau.json',emptyColumn:false,databaseName:'nassaus'},
  // {value:'',slug:'',jsonName:'new-reliance.json',emptyColumn:false,databaseName:'newreliances'},
  // {value:'',slug:'',jsonName:'new-york-wholesale.json',emptyColumn:false,databaseName:'newyorkwholesales'},
  // {value:'',slug:'',jsonName:'nirav-indian-groceries.json',emptyColumn:false,databaseName:'niravindiangroceries'},
  // {value:'',slug:'',jsonName:'nupur.json',emptyColumn:false,databaseName:'nupurs'},
  // {value:'',slug:'',jsonName:'ny-zara-food-inc.json',emptyColumn:false,databaseName:'nyzarafoodincs'},
  // {value:'',slug:'',jsonName:'ontime.json',emptyColumn:false,databaseName:'ontimes'},
  // {value:'',slug:'',jsonName:'optimal.json',emptyColumn:false,databaseName:'optimals'},
  // {value:'',slug:'',jsonName:'pams.json',emptyColumn:false,databaseName:'pams'},
  // {value:'',slug:'',jsonName:'pexco.json',emptyColumn:false,databaseName:'pexcos'},
  // {value:'',slug:'',jsonName:'pgl-trade.json',emptyColumn:false,databaseName:'pgltrades'},
  // {value:'',slug:'',jsonName:'preferred-beverage.json',emptyColumn:false,databaseName:'preferredbeverages'},
  // {value:'',slug:'',jsonName:'priya-foods-usa.json',emptyColumn:false,databaseName:'priyafoodsusas'},
  // {value:'',slug:'',jsonName:'produce-n-more.json',emptyColumn:false,databaseName:'producenmores'},
  // {value:'',slug:'',jsonName:'pure-ghee.json',emptyColumn:false,databaseName:'pureghees'},
  // {value:'',slug:'',jsonName:'putull-dist.json',emptyColumn:false,databaseName:'putulldists'},
  // {value:'',slug:'',jsonName:'radhey-foods.json',emptyColumn:false,databaseName:'radheyfoods'},
  // {value:'',slug:'',jsonName:'raja-foods.json',emptyColumn:false,databaseName:'rajafoods'},
  // {value:'',slug:'',jsonName:'rane-music.json',emptyColumn:false,databaseName:'ranemusics'},
  // {value:'',slug:'',jsonName:'rite-source-corp.json',emptyColumn:false,databaseName:'ritesourcecorps'},
  // {value:'',slug:'',jsonName:'rite-source.json',emptyColumn:false,databaseName:'ritesources'},
  // {value:'',slug:'',jsonName:'riya.json',emptyColumn:false,databaseName:'riyas'},
  // {value:'',slug:'',jsonName:'rollin-diary.json',emptyColumn:false,databaseName:'rollindiaries'},
  // {value:'',slug:'',jsonName:'ron-foods.json',emptyColumn:false,databaseName:'ronfoods'},
  // {value:'',slug:'',jsonName:'ron.json',emptyColumn:false,databaseName:'rons'},
  // {value:'',slug:'',jsonName:'sankaj.json',emptyColumn:false,databaseName:'sankajs'},
  {
    value: "Sea mark",
    slug: "sea-mark",
    jsonName: "seamark.json",
    emptyColumn: false,
    databaseName: "seamarks",
  },
  // {value:'',slug:'',jsonName:'shakti.json',emptyColumn:false,databaseName:'shaktis'},
  // {value:'',slug:'',jsonName:'shata.json',emptyColumn:false,databaseName:'shatas'},
  // {value:'',slug:'',jsonName:'shine.json',emptyColumn:false,databaseName:'shines'},
  // {value:'',slug:'',jsonName:'shreeji.json',emptyColumn:false,databaseName:'shreejis'},
  // {value:'',slug:'',jsonName:'singh-and-singh.json',emptyColumn:false,databaseName:'singhandsinghs'},
  // {value:'',slug:'',jsonName:'slaughter-house.json',emptyColumn:false,databaseName:'slaughterhouses'},
  // {value:'',slug:'',jsonName:'spicy-sense.json',emptyColumn:false,databaseName:'spicysenses'},
  // {value:'',slug:'',jsonName:'spicy-world.json',emptyColumn:false,databaseName:'spicyworlds'},
  // {value:'',slug:'',jsonName:'surati.json',emptyColumn:false,databaseName:'suratis'},
  // {value:'',slug:'',jsonName:'symco-distributor.json',emptyColumn:false,databaseName:'symcodistributors'},
  // {value:'',slug:'',jsonName:'temin.json',emptyColumn:false,databaseName:'temins'},
  // {value:'',slug:'',jsonName:'turkana.json',emptyColumn:false,databaseName:'turkanas'},
  // {value:'',slug:'',jsonName:'two-brother-wholesale.json',emptyColumn:false,databaseName:'twobrotherwholesales'},
  // {value:'',slug:'',jsonName:'unique-importer.json',emptyColumn:false,databaseName:'uniqueimporters'},
  // {value:'',slug:'',jsonName:'us-gourmet-food.json',emptyColumn:false,databaseName:'usgourmetfoods'},
  // {value:'',slug:'',jsonName:'usa-halal.json',emptyColumn:false,databaseName:'usahalals'},
  // {value:'',slug:'',jsonName:'vadilal.json',emptyColumn:false,databaseName:'vadilals'},
  // {value:'',slug:'',jsonName:'vibrant.json',emptyColumn:false,databaseName:'vibrants'},
  // {value:'',slug:'',jsonName:'vidyas.json',emptyColumn:false,databaseName:'vidyas'},
  // {value:'',slug:'',jsonName:'vijay-home-foods.json',emptyColumn:false,databaseName:'vijayhomefoods'},
  // {value:'',slug:'',jsonName:'vintage.json',emptyColumn:false,databaseName:'vintages'},
  // {value:'',slug:'',jsonName:'wave-ron-foods.json',emptyColumn:false,databaseName:'waveronfoods'}
];