export const dropdownOptions = [
  { value: "Chetak", slug: "chetak" },
  // { value: "Laxmi", slug: "laxmi" },
  { value: "Sea Mark", slug: "sea-mark" },
  { value: "Best Foods", slug: "best-foods" },
  { value: "Krishna Foods", slug: "krishna-foods" },
  { value: "Joy Gourmet Foods", slug: "joy-gourmet-foods" },
  { value: "Advance Foods", slug: "advance-foods" },
  {value:"Katzam Foods",slug:"katzam-foods"},
  //{value:"Baroody Imports",slug:"baroody"},
  {value:"East End Groceries",slug:"east-end"},
  {value:"Indian Spice Trading",slug:"indian-spice-trading"},
  {value:"Grocermill",slug:"grocer-mill"},
  {value:"Meenaxi Enterprise",slug:"meenaxi-enterprise"},
  //{value:"Rajbhog Foods",slug:"rajbhog-food"},
 // {value:"Moda Food",slug:"moda-food"},
 // {value:"US Gourmet Food",slug:"us-gourmet-food"},
 // {value:"Delight Foods",slug:"delight-food"},
  {value:"Jalaram Produce",slug:"jalaram-produce"},
//  {value:"Vijay Home Foods",slug:"vijay-food"},
//  {value:"Radhey Foods",slug:"radhey-food"},
 // {value:"Vintage Food",slug:"vintage-food"},
 // {value:"Delight Distribution",slug:"delight-distribution"},
  //{value:"DSA Snacks",slug:"dsa-snacks"},
  //{value:"Dawn Food",slug:"dawn-food"},

];
