export const dropdownOptions = [
  {
    value: "Chetak",
    slug: "chetak",
    jsonName: "chetak-products.json",
    emptyColumn: true,
    databaseName: "chetakproducts",
  },
  {
    value: "Aahubarah USA",
    slug: "aahubarah-usa",
    jsonName: "aahubarah.json",
    emptyColumn: false,
    databaseName: "aahubarahs",
  },
  {
    value: "Adelman foods",
    slug: "adelman-foods",
    jsonName: "adelaman-food.json",
    emptyColumn: false,
    databaseName: "adelamanfoods",
  },
  {
    value: "Advance Foods",
    slug: "advance-foods",
    jsonName: "advance-foods.json",
    emptyColumn: false,
    databaseName: "advancefoods",
  },
  {
    value: "Aliments",
    slug: "aliments",
    jsonName: "aliments.json",
    emptyColumn: false,
    databaseName: "aliments",
  },
  {
    value: "Amtrade",
    slug: "amtrade",
    jsonName: "amtrade.json",
    emptyColumn: false,
    databaseName: "amtrades",
  },
  {
    value: "Anmol distributors",
    slug: "anmol-distributors",
    jsonName: "anmol-distribution.json",
    emptyColumn: false,
    databaseName: "anmoldistributions",
  },
  {
    value: "Anns eco store",
    slug: "anns-eco-store",
    jsonName: "anns-eco-store.json",
    emptyColumn: false,
    databaseName: "annsecostores",
  },
  {
    value: "Babco foods",
    slug: "babco-foods",
    jsonName: "babco.json",
    emptyColumn: false,
    databaseName: "babcos",
  },
  {
    value: "Baraka cold",
    slug: "baraka-cold",
    jsonName: "baraka-cold.json",
    emptyColumn: false,
    databaseName: "barakacolds",
  },
  {
    value: "Barlett dairy",
    slug: "bartlett-dairy",
    jsonName: "barlett.json",
    emptyColumn: false,
    databaseName: "barletts",
  },
  {
    value: "Baroody",
    slug: "baroody",
    jsonName: "baroody.json",
    emptyColumn: true,
    databaseName: "baroodies",
  },
  // {value:'',slug:'',jsonName:'bartlett.json',emptyColumn:false,databaseName:'bartletts'},
  {
    value: "Bedessee",
    slug: "bedessee",
    jsonName: "bedessee.json",
    emptyColumn: false,
    databaseName: "bedessees",
  },
  // {value:'',slug:'',jsonName:'Best-food-1.json',emptyColumn:false,databaseName:'bestfood1'},
  {
    value: "Best Foods",
    slug: "best-foods",
    jsonName: "best-foods.json",
    emptyColumn: true,
    databaseName: "bestfoods",
  },

  {
    value: "Dara food",
    slug: "dara-food",
    jsonName: "dara.json",
    emptyColumn: false,
    databaseName: "daras",
  },
  {
    value: "Dawn food",
    slug: "dawn-food",
    jsonName: "dawn-food.json",
    emptyColumn: false,
    databaseName: "dawnfoods",
  },
  {
    value: "Delight distribution",
    slug: "delight-distribution",
    jsonName: "delight-distrubution.json",
    emptyColumn: false,
    databaseName: "delightdistrubutions",
  },
  {
    value: "Delight foods",
    slug: "delight-food",
    jsonName: "delight-foods.json",
    emptyColumn: true,
    databaseName: "delightfoods",
  },
  {
    value: "Dsa snacks",
    slug: "dsa-snacks",
    jsonName: "dsa-snacks.json",
    emptyColumn: false,
    databaseName: "dsasnacks",
  },
  {
    value: "East end",
    slug: "east-end",
    jsonName: "east-end.json",
    emptyColumn: false,
    databaseName: "eastends",
  },
  {
    value: "Empire food importers",
    slug: "empire-food-importers",
    jsonName: "empire-food-importers.json",
    emptyColumn: false,
    databaseName: "empirefoodimporters",
  },
  {
    value: "Family five",
    slug: "family-five",
    jsonName: "family-five.json",
    emptyColumn: false,
    databaseName: "familyfives",
  },
  {
    value: "Galil imports",
    slug: "galil",
    jsonName: "galil-importing.json",
    emptyColumn: false,
    databaseName: "galilimportings",
  },
  {
    value: "Goyal group",
    slug: "goyal-group",
    jsonName: "goyal-grp.json",
    emptyColumn: true,
    databaseName: "goyalgrps",
  },
  {
    value: "Grocer mill",
    slug: "grocer-mill",
    jsonName: "grocermill.json",
    emptyColumn: true,
    databaseName: "grocermills",
  },
  {
    value: "Hellenic",
    slug: "hellenic",
    jsonName: "hellenic.json",
    emptyColumn: false,
    databaseName: "hellenics",
  },
  {
    value: "Hill top farms",
    slug: "hill-top-farms",
    jsonName: "hill-top-farms.json",
    emptyColumn: false,
    databaseName: "hilltopfarms",
  },
  {
    value: "House of spices",
    slug: "house-of-spices",
    jsonName: "house-spices.json",
    emptyColumn: false,
    databaseName: "housespices",
  },
  {
    value: "Indian food & spices",
    slug: "indian-food-and-spices",
    jsonName: "india-food-spices.json",
    emptyColumn: false,
    databaseName: "indiafoodspices",
  },
  {
    value: "Indian spice trading",
    slug: "indian-spice-trading",
    jsonName: "indian-spice-trading.json",
    emptyColumn: true,
    databaseName: "indianspicetradings",
  },
  {
    value: "I sifol",
    slug: "i-sifol",
    jsonName: "I-sifol-llc.json",
    emptyColumn: false,
    databaseName: "isifolllcs",
  },
  {
    value: "Jaan distributors",
    slug: "jaan-distributors",
    jsonName: "jaan-dist.json",
    emptyColumn: false,
    databaseName: "jaandists",
  },
  {
    value: "Jalaram produce",
    slug: "jalaram-produce",
    jsonName: "jalaram.json",
    emptyColumn: false,
    databaseName: "jalarams",
  },
  {
    value: "JCW imports",
    slug: "jcw-import-and-export",
    jsonName: "jcw-import.json",
    emptyColumn: false,
    databaseName: "jcwimports",
  },
  // {value:'',slug:'',jsonName:'joy-foods.json',emptyColumn:false,databaseName:'joyfoods'},
  {
    value: "Joy gourmet foods",
    slug: "joy-gourment-foods",
    jsonName: "joy-gourmet-foods.json",
    emptyColumn: true,
    databaseName: "joygourmetfoods",
  },
  {
    value: "Katzman",
    slug: "katzam-foods",
    jsonName: "katzman.json",
    emptyColumn: false,
    databaseName: "katzman",
  },
  {
    value: "KM Distribution",
    slug: "km-distribution-usa",
    jsonName: "km-dist-usa.json",
    emptyColumn: false,
    databaseName: "kmdistusas",
  },
  {
    value: "Koryeo",
    slug: "koryeo",
    jsonName: "koryeo-foods.json",
    emptyColumn: false,
    databaseName: "koryeofoods",
  },
  {
    value: "Krinos foods",
    slug: "krinos-foods",
    jsonNaseame: "krino-foods.json",
    emptyColumn: false,
    databaseName: "krinofoods",
  },
  {
    value: "Krishna Foods",
    slug: "krishna-food-corp",
    jsonName: "krishna-foods-products.json",
    emptyColumn: true,
    databaseName: "krishnafoodsproducts",
  },
  // {value:'',slug:'',jsonName:'krishna.json',emptyColumn:false,databaseName:'krishnas'},
  {
    value: "Leblon foods",
    slug: "leblon-foods",
    jsonName: "leblon.json",
    emptyColumn: false,
    databaseName: "leblons",
  },
  {
    value: "Loumidis foods",
    slug: "loumidis-foods",
    jsonName: "loumidis-food.json",
    emptyColumn: false,
    databaseName: "loumidisfoods",
  },
  {
    value: "Maharaja food importers",
    slug: "maharaja-food-importers",
    jsonName: "maharaja.json",
    emptyColumn: false,
    databaseName: "maharajas",
  },
  {
    value: "Meenaxi enterprise",
    slug: "meenaxi-enterprise",
    jsonName: "meenaxi.json",
    emptyColumn: true,
    databaseName: "meenaxis",
  },
  {
    value: "Mels ice-cream",
    slug: "mels-ice-cream",
    jsonName: "mel-icecream.json",
    emptyColumn: false,
    databaseName: "melicecreams",
  },
  {
    value: "Moda food",
    slug: "moda-food",
    jsonName: "moda-food-ny.json",
    emptyColumn: false,
    databaseName: "modafoodnies",
  },
  {
    value: "Mr pickle",
    slug: "mr-pickle",
    jsonName: "mr-pickle.json",
    emptyColumn: false,
    databaseName: "mrpickles",
  },
  // {value:'',slug:'',jsonName:'my-baby-ev.json',emptyColumn:false,databaseName:'mybabyevs'},
  {
    value: "Nassau candy",
    slug: "nassau-candy",
    jsonName: "nassau.json",
    emptyColumn: false,
    databaseName: "nassaus",
  },
  {
    value: "New reliance traders",
    slug: "new-reliance-traders",
    jsonName: "new-reliance.json",
    emptyColumn: true,
    databaseName: "newreliances",
  },
  {
    value: "New york wholesale",
    slug: "new-york-wholesale",
    jsonName: "new-york-wholesale.json",
    emptyColumn: false,
    databaseName: "newyorkwholesales",
  },
  {
    value: "Nirav Indian groceries",
    slug: "nirav-indian-groceries",
    jsonName: "nirav-indian-groceries.json",
    emptyColumn: false,
    databaseName: "niravindiangroceries",
  },
  {
    value: "Nupur trading",
    slug: "nupur-trading",
    jsonName: "nupur.json",
    emptyColumn: false,
    databaseName: "nupurs",
  },
  {
    value: "NY zara food",
    slug: "ny-zara-food",
    jsonName: "ny-zara-food-inc.json",
    emptyColumn: false,
    databaseName: "nyzarafoodincs",
  },
  {
    value: "On time distribution",
    slug: "on-time-distribution",
    jsonName: "ontime.json",
    emptyColumn: false,
    databaseName: "ontimes",
  },
  {
    value: "Optima foods",
    slug: "optima-foods",
    jsonName: "optimal.json",
    emptyColumn: false,
    databaseName: "optimals",
  },
  {
    value: "Pams creations",
    slug: "pams-creations",
    jsonName: "pams.json",
    emptyColumn: false,
    databaseName: "pams",
  },
  {
    value: "Pexco INC.",
    slug: "pexco-inc",
    jsonName: "pexco.json",
    emptyColumn: false,
    databaseName: "pexcos",
  },
  {
    value: "PGL trade",
    slug: "pgl-trade",
    jsonName: "pgl-trade.json",
    emptyColumn: false,
    databaseName: "pgltrades",
  },
  {
    value: "Preferred beverage",
    slug: "referred-beverage",
    jsonName: "preferred-beverage.json",
    emptyColumn: false,
    databaseName: "preferredbeverages",
  },
  {
    value: "Priya foods",
    slug: "priya-foods",
    jsonName: "priya-foods-usa.json",
    emptyColumn: true,
    databaseName: "priyafoodsusas",
  },
  {
    value: "Produce n More",
    slug: "produce-n-more",
    jsonName: "produce-n-more.json",
    emptyColumn: false,
    databaseName: "producenmores",
  },
  // {value:'',slug:'',jsonName:'pure-ghee.json',emptyColumn:false,databaseName:'pureghees'},
  {
    value: "Putul distributors",
    slug: "putul-distributors",
    jsonName: "putull-dist.json",
    emptyColumn: false,
    databaseName: "putulldists",
  },
  {
    value: "Radhey foods",
    slug: "radhey-food",
    jsonName: "radhey-foods.json",
    emptyColumn: false,
    databaseName: "radheyfoods",
  },
  {
    value: "Raja foods",
    slug: "raja-foods",
    jsonName: "raja-foods.json",
    emptyColumn: false,
    databaseName: "rajafoods",
  },
  {
    value: "Rane music",
    slug: "ranemusic",
    jsonName: "rane-music.json",
    emptyColumn: false,
    databaseName: "ranemusics",
  },
  {
    value: "Rite source corp",
    slug: "ritesource-corp",
    jsonName: "rite-source-corp.json",
    emptyColumn: false,
    databaseName: "ritesourcecorps",
  },
  // {value:'',slug:'',jsonName:'rite-source.json',emptyColumn:false,databaseName:'ritesources'},
  // {value:'',slug:'',jsonName:'riya.json',emptyColumn:false,databaseName:'riyas'},
  {
    value: "Rollin dairy",
    slug: "rollin-dairy",
    jsonName: "rollin-diary.json",
    emptyColumn: false,
    databaseName: "rollindiaries",
  },
  {
    value: "Ron foods",
    slug: "ron-foods",
    jsonName: "ron-foods.json",
    emptyColumn: false,
    databaseName: "ronfoods",
  },
  // {value:'',slug:'',jsonName:'ron.json',emptyColumn:false,databaseName:'rons'},
  {
    value: "Sankaj",
    slug: "sankaj",
    jsonName: "sankaj.json",
    emptyColumn: false,
    databaseName: "sankajs",
  },
  {
    value: "Sea mark",
    slug: "sea-mark",
    jsonName: "seamark.json",
    emptyColumn: false,
    databaseName: "seamarks",
  },
  {
    value: "Shakti group",
    slug: "shakti-group-usa",
    jsonName: "shakti.json",
    emptyColumn: false,
    databaseName: "shaktis",
  },
  {
    value: "Shata traders",
    slug: "shata-traders",
    jsonName: "shata.json",
    emptyColumn: true,
    databaseName: "shatas",
  },
  {
    value: "Shine foods",
    slug: "shine-foods",
    jsonName: "shine.json",
    emptyColumn: false,
    databaseName: "shines",
  },
  {
    value: "Shreeji",
    slug: "shreeji",
    jsonName: "shreeji.json",
    emptyColumn: false,
    databaseName: "shreejis",
  },
  // {value:'',slug:'',jsonName:'singh-and-singh.json',emptyColumn:false,databaseName:'singhandsinghs'},
  {
    value: "Slaughter house",
    slug: "slaughter-house",
    jsonName: "slaughter-house.json",
    emptyColumn: false,
    databaseName: "slaughterhouses",
  },
  {
    value: "Spicy sense",
    slug: "spicy-sense",
    jsonName: "spicy-sense.json",
    emptyColumn: false,
    databaseName: "spicysenses",
  },
  {
    value: "Spicy world",
    slug: "spicy-world",
    jsonName: "spicy-world.json",
    emptyColumn: false,
    databaseName: "spicyworlds",
  },
  {
    value: "Surati",
    slug: "surati",
    jsonName: "surati.json",
    emptyColumn: false,
    databaseName: "suratis",
  },
  {
    value: "Symco distributor",
    slug: "symco-distributor",
    jsonName: "symco-distributor.json",
    emptyColumn: false,
    databaseName: "symcodistributors",
  },
  {
    value: "Temin distribution",
    slug: "temin-distribution",
    jsonName: "temin.json",
    emptyColumn: false,
    databaseName: "temins",
  },
  {
    value: "Turkana food",
    slug: "turkana-food",
    jsonName: "turkana.json",
    emptyColumn: false,
    databaseName: "turkanas",
  },
  {
    value: "Two brother wholesale",
    slug: "two-brother-wholesale",
    jsonName: "two-brother-wholesale.json",
    emptyColumn: false,
    databaseName: "twobrotherwholesales",
  },
  {
    value: "Unique importer",
    slug: "unique-importer",
    jsonName: "unique-importer.json",
    emptyColumn: false,
    databaseName: "uniqueimporters",
  },
  {
    value: "US gourmet",
    slug: "us-gourmet-food",
    jsonName: "us-gourmet-food.json",
    emptyColumn: false,
    databaseName: "usgourmetfoods",
  },
  {
    value: "USA Halal",
    slug: "usa-halal-foods",
    jsonName: "usa-halal.json",
    emptyColumn: false,
    databaseName: "usahalals",
  },
  {
    value: "Vadilal",
    slug: "vadilal",
    jsonName: "vadilal.json",
    emptyColumn: false,
    databaseName: "vadilals",
  },
  {
    value: "Vibrant enterprise",
    slug: "vibrant-enterprise",
    jsonName: "vibrant.json",
    emptyColumn: false,
    databaseName: "vibrants",
  },
  {
    value: "Vidyas",
    slug: "vidyas",
    jsonName: "vidyas.json",
    emptyColumn: false,
    databaseName: "vidyas",
  },
  {
    value: "Vijay home foods",
    slug: "vijay-food",
    jsonName: "vijay-home-foods.json",
    emptyColumn: false,
    databaseName: "vijayhomefoods",
  },
  {
    value: "Vintage food",
    slug: "vintage-food",
    jsonName: "vintage.json",
    emptyColumn: false,
    databaseName: "vintages",
  },
  // {value:'',slug:'',jsonName:'wave-ron-foods.json',emptyColumn:false,databaseName:'waveronfoods'}
];
